#!/usr/bin/env bash

set -o errexit  # Exit on error. Append "|| true" if you expect an error.
set -o errtrace # Exit on error inside any functions or subshells.

# Magic below...
export IFS=$'\n'
curpath=${NAUTILUS_SCRIPT_CURRENT_URI#file://}
files=$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
cd "$curpath"


# Even more magic...
tmpfile=$(mktemp)
exec > $tmpfile
exec 2>&1
function debug_std () {
    cat $tmpfile | grep -v 'Gtk-' | grep -v '^$' | zenity --text-info --title="Log Output" #--filename=$tmpfile
}
trap debug_std QUIT INT TERM EXIT


# Main code below...
echo "PWD: $PWD"
git init
git remote add origin "https://github.com/esauvisky/"$(zenity --entry --text="Please insert your GitHub repository name:" --title="GitHub")".git"
git remote -v
git fetch
git checkout master
#git pull --allow-unrelated-histories
for file in "$@"; do
    echo "git add "$file""
    git add "$file"
done
git commit -m "Merging local files" -v
git push