#!/usr/bin/env bash
set -o errexit; set -o errtrace; set -o pipefail # Exit on errors

#$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS - new line separated file paths; passed on by Nautilus on Gnome 2.2
# echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"

catt stop
while read line; do
    file=$line
    catt cast "$file"
done <<< $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
