%YAML 1.3
---
- Rule:
  - Process: ghidra
  - Rule:
    - Key: [Back Button, pressed]
    - KeyPress:
      - [Alt_L, Left]
      - click
  - Rule:
    - Key: [Forward Button, pressed]
    - KeyPress:
      - [Alt_L, Right]
      - click
- Or:
  - Rule:
    - Key: [Back Button, pressed]
    - MouseClick: [button8, 1]
  - Rule:
    - Key: [Forward Button, pressed]
    - MouseClick: [button9, 1]
...
---
- Rule:
  - Key: [Mouse Gesture Button, pressed]
  - Set:
    - null
    - scroll-ratchet
    - 1
- Rule:
  - Key: [Mouse Gesture Button, released]
  - Set:
    - null
    - scroll-ratchet
    - 2
...
